### ISSUE TITLE
ChamferHeight Modifier does not appear on iOS Build

### ISSUE THREAD

**Issue by gangstageek** [mapbox/mapbox-unity-sdk#1709]
So the chamfer modifier works in editor but not on build.

![Screen Shot 2020-10-28 at 10 35 41 PM](https://user-images.githubusercontent.com/11141830/97530128-acbb8700-196e-11eb-9a51-485fcb1b73fb.png)
![Screen Shot 2020-10-28 at 11 03 59 PM](https://user-images.githubusercontent.com/11141830/97531689-f063c000-1971-11eb-8c82-d016fc63fdf7.png)
![Screen Shot 2020-10-28 at 10 36 23 PM](https://user-images.githubusercontent.com/11141830/97530136-b04f0e00-196e-11eb-995a-6e436efb8d1d.png)

This is the error in Xcode
`NullReferenceException: Object reference not set to an instance of an object.
  at Mapbox.Unity.MeshGeneration.Modifiers.PolygonMeshModifier.Run (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData md, Mapbox.Unity.MeshGeneration.Data.UnityTile tile) [0x00000] in <00000000000000000000000000000000>:0 
  at Mapbox.Unity.MeshGeneration.Modifiers.ModifierStack.Execute (Mapbox.Unity.MeshGeneration.Data.UnityTile tile, Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData meshData, UnityEngine.GameObject parent, System.String type) [0x00000] in <00000000000000000000000000000000>:0 
  at Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer.ProcessFeature (System.Int32 index, Mapbox.Unity.MeshGeneration.Data.UnityTile tile, Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizerProperties layerProperties, System.Single layerExtent) [0x00000] in <00000000000000000000000000000000>:0 
  at Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer+<ProcessLayer>d__37.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at Mapbox.Unity.Utilities.Runnable+Routine.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 `

Unity 2019.3.14f1
Universal RP 7.3.1
IL2Cpp
.Net 4.x
iOS 12.0

**Comment by brnkhy** [comment]
@gangstageek that's interesting. I cannot imagine what might be wrong, I mean specific to platform. Do you remember what was the null object?

**Comment by gangstageek** [comment]
@brnkhy  So this only happens when I build. It seems like it has something to do with the Chamfer Height Modifier script. Debugging things in Xcode from Unity is pretty difficult. That debug log is the best I can do. Does this have something to do with the scriptable object? Does it need to be at a certain location in the project folder? The null is coming from Mapbox.Unity.MeshGeneration.Modifiers.PolygonMeshModifier.Run.... any help will do

**Comment by gangstageek** [comment]
This is from Mapbox.Unity.MeshGeneration.Modifiers.PolygonMeshModifier.Run from ChamferHeightModifier.cs  and I am assuming that one of those parameters are null.

`public override void Run(VectorFeatureUnity feature, MeshData md, UnityTile tile = null)
		{
			if (md.Vertices.Count == 0 || feature == null || feature.Points.Count < 1)
				return;

			var minHeight = 0f;
			float hf = _height;

			if (!_forceHeight)
			{
				GetHeightData(feature, tile.TileScale, ref minHeight, ref hf);
			}

			var max = md.Vertices[0].y;
			var min = md.Vertices[0].y;
			if (_flatTops)
			{
				FlattenTops(md, minHeight, ref hf, ref max, ref min);
			}
			else
			{
				for (int i = 0; i < md.Vertices.Count; i++)
				{
					md.Vertices[i] = new Vector3(md.Vertices[i].x, md.Vertices[i].y + minHeight + hf, md.Vertices[i].z);
				}
			}

			var originalVertexCount = md.Vertices.Count;
			Chamfer(feature, md, tile);

			Sides(feature, md, hf, originalVertexCount);
		}`

**Comment by gangstageek** [comment]
@brnkhy  So since I haven't heard from anyone on how to fix this. Is there a work around I can do to bake normal maps textures for the building edges? And if so how can I go about that?

**Comment by trancaothongdev** [comment]
this problem has been solved

**Comment by trancaothongdev** [comment]
Has this issue been resolved yet?

**Comment by brnkhy** [comment]
I'm sorry I have no idea how I missed this before but I'm afraid it's not solved and it's likely that you are better using regular buildings for now.
